Nama : Zainul Abad
NIM  : 160411100116
Kelas: Penambangan dan Pencarian Web

======================================================================================================

**Cara melakukan scraping website.
Website : https://www.gudangkamera.net/

**Tujuan Scraping website : Memperoleh data Jenis kamera dan harga kamera.

**Tools :
1. jupyter notebook 5.5.0 (include pada Anaconda 3)
2. Library Python ( Beautiful Soup / bs4, sqlite3, urllib) library tersebut include pada Anaconda

**Langkah - Langkah Scraping web :
1. Tentukan website yang akan di Scraping ( https://www.gudangkamera.net/ )
2. Menentukan top level url web yang akan di scrapping untuk mendapatkan source code html
    ( https://www.gudangkamera.net/search?keywords=kamera )
3. Inisialisasi ulrllib, membuat source code seperti dibawah :

In [12]:
from urllib.request import urlopen
html = urlopen("https://www.gudangkamera.net/search?keywords=kamera").read()
print(type(html))
print(html[1:1000])

<class 'bytes'>
b'!DOCTYPE html>\n<html>\n<head>\n    <meta charset="utf-8"/>\n    <title>Hasil Pencarian dari "kamera" - Gudang Kamera </title>\n\n    <meta name="keywords" content="Gudang Kamera surabaya , malang , jakarta, jual aksesoris dan kamera terpercaya, pelayanan terbaik, Koleksi lensa dan kamera terlengkap"/>\n    <meta name="description" content="Gudang Kamera surabaya , malang , jakarta - Pusat kamera second terlengkap di surabaya , malang , jakarta  - Toko kamera second - Toko kamera surabaya , malang , jakarta - Toko kamera second paling komplit di surabaya , malang , jakarta - pelayanan terbaik Koleksi lensa dan kamera terlengkap"/>\n    <meta name="author" content="Gudang Kamera surabaya , malang , jakarta"/>\n    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0"/>\n    <meta property="og:title" content="Hasil Pencarian dari "kamera" - Gudang Kamera "/>\n    <meta property="og:image" content="https://www.gudangkamera.net/img/logo.png"/>\n    <met'

*urllib adalah library python yang digunakan untuk mengakses web, sedangkan fungsi urlopen() dan read() digunakan untuk membaca HTML yang dikonversi dalam format String.

4. Kemudian inisialisasi Beautiful Soup, membuat source code Beautiful Soup seperti dibawah :

In [13]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(html, "lxml")
print(type(soup))
print(soup.prettify()[1:1000])

<class 'bs4.BeautifulSoup'>
!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <title>
   Hasil Pencarian dari "kamera" - Gudang Kamera
  </title>
  <meta content="Gudang Kamera surabaya , malang , jakarta, jual aksesoris dan kamera terpercaya, pelayanan terbaik, Koleksi lensa dan kamera terlengkap" name="keywords"/>
  <meta content="Gudang Kamera surabaya , malang , jakarta - Pusat kamera second terlengkap di surabaya , malang , jakarta  - Toko kamera second - Toko kamera surabaya , malang , jakarta - Toko kamera second paling komplit di surabaya , malang , jakarta - pelayanan terbaik Koleksi lensa dan kamera terlengkap" name="description"/>
  <meta content="Gudang Kamera surabaya , malang , jakarta" name="author"/>
  <meta content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" name="viewport"/>
  <meta content="Hasil Pencarian dari " gudang="" kamera="" property="og:title"/>
  <meta content="https://www.gudangkamera.net/img/logo.png" property="og:image"/>
  <meta content="produc

*Inisialisasi Beautiful Soup digunakan untuk membantu dalam proses web scraping digunakan modul beautifulsoup
Pertama tama diimport dahulu modulnya, lalu string html diubah menjadi objek beautifulsoup dan digunakan parser lxml
dan digunakan untuk menelusuri setiap elemnnya.

5. kemudian telusuri setiap tag "li" yang yang mempunyai class "col-lg-3 col-sm-3 col-xs-4".kemudian ambil atribut yang dibutuhkan yaitu nama dan harga pada tag 'div' yang mempunyai class 'shop-item-summary text-center'.

In [14]:
nama = soup.find_all("li","col-lg-3 col-sm-3 col-xs-4")
i = 1
for p in nama:
    print(p.find('div','shop-item-summary text-center').get_text())

LENSA CANON 17-40MM F/4 L KODE UV


Rp. 6.000.000





LENSA SIGMA 50-100MM F1.8 (3836)


Rp. 11.850.000





LENSA CANON 70-200MM F/4 L USM KODE UT


Rp. 6.000.000





FUJIFILM X-M1 (9066)   LENSA 16-50MM


Rp. 4.000.000





LENSA FUJIFILM XF 35MM F/2 WR (7439)


Rp. 4.500.000





CANON 50D (6478)   LENSA 18-55MM SC 18XXX


Rp. 4.800.000





LIKE-NEW - Canon RF 50mm f1.2L USM - 0960


Rp. 32.000.000





Secondhand - Nikon AFS 55-200mm VR II - 4014


Rp. 1.950.000





NEW - MADA_1432 Hand Strap Carabiner


Rp. 100.000





Secondhand -Canon EF 70-200mm f2.8L IS II USM - 4870


Rp. 19.900.000





FUJIFILM X-T20 SILVER (1358)


Rp. 9.250.000





FUJIFILM X-T20 (2082)


Rp. 9.250.000





Canon 5D Mark III / 5D III BO SC 9rb- Mint Condition |5370|


Rp. 22.850.000





Fujifilm X-A3 / Xa3 KIT 16-50MM - MINT CONDITION |3719|


Rp. 6.300.000





Sony A6000 Black Kit 16-50mm 3.5-5.6 OSS - MINT CONDITION |


Rp. 6.650.000





Canon Eos 70D BO - MINT CONDITION | 2672|


Rp. 7.700.000





[SECONDHAND] Canon EOS 70D WiFi - BO 3187


Rp. 6.500.000





Nikon D3400 Kit 18-55mm - GOOD CONDITION |0892|


Rp. 4.850.000





Sony A7 / Alpha7 BO - MINT CONDITION |2377|


Rp. 9.600.000





Canon 60D BO - MINT CONDITION |6887 |


Rp. 6.300.000

6. Kemudian kita membuat source code pandas DataFrame digunakan untuk membuat sebuah data set
    "pada pandas ini saya membuat list untuk data set"

7. Pada source code dibawah saya juga membuat import ke sqlite yaitu saya membuat database baru dengan nama "gudangkamera.db".

import sqlite3
conn = sqlite3.connect('gudangkamera.db')
c = conn.cursor(). 
 
kemudian pada database itu saya membuat tabel dengan nama "kamera" 
(#create Table
c.execute('DROP TABLE IF EXISTS kamera')
c.execute('''CREATE TABLE IF NOT EXISTS kamera(nama VARCHAR, harga INTERGER)''')
conn.commit()
). 

kemudian data set di insertkan pada tabel "kamera" 
(c.execute("INSERT INTO kamera (nama, harga) values (?, ?)", (nama_produk[ii], harga_produk[ii]))
    conn.commit()
    ii+=1)

In [15]:
import pandas as pd

import sqlite3
conn = sqlite3.connect('gudangkamera.db')
c = conn.cursor()

#create Table
c.execute('DROP TABLE IF EXISTS kamera')
c.execute('''CREATE TABLE IF NOT EXISTS kamera(nama VARCHAR, harga INTERGER)''')
conn.commit()

nama_produk = []
harga_produk = []


produk = soup.find_all("li","col-lg-3 col-sm-3 col-xs-4")
ii=0
for p in produk:
    nama = p.find('div', 'shop-item-summary text-center').get_text().encode('utf-8')
    nama=str(nama)
    nama=nama.replace("b'","")
    for i in range(3):
        nama=nama.replace("\\n\\n","\\n")
    nama=nama.split('\\n')
    nama_produk.append(nama[1])
    harga_produk.append(int(nama[2].replace('Rp','').replace('.','').replace('.','')))
   
    
    
    c.execute("INSERT INTO kamera (nama, harga) values (?, ?)", (nama_produk[ii], harga_produk[ii]))
    conn.commit()
    ii+=1
    
produk_dict = {'nama':nama_produk,'harga':harga_produk}
df = pd.DataFrame(produk_dict, columns = ['nama','harga'])

df.sort_values('nama')

                                                 nama     harga
5           CANON 50D (6478)   LENSA 18-55MM SC 18XXX   4800000
12  Canon 5D Mark III / 5D III BO SC 9rb- Mint Con...  22850000
19              Canon 60D BO - MINT CONDITION |6887 |   6300000
15          Canon Eos 70D BO - MINT CONDITION | 2672|   7700000
3                FUJIFILM X-M1 (9066)   LENSA 16-50MM   4000000
11                              FUJIFILM X-T20 (2082)   9250000
10                       FUJIFILM X-T20 SILVER (1358)   9250000
13  Fujifilm X-A3 / Xa3 KIT 16-50MM - MINT CONDITI...   6300000
0                   LENSA CANON 17-40MM F/4 L KODE UV   6000000
2              LENSA CANON 70-200MM F/4 L USM KODE UT   6000000
4                LENSA FUJIFILM XF 35MM F/2 WR (7439)   4500000
1                    LENSA SIGMA 50-100MM F1.8 (3836)  11850000
6           LIKE-NEW - Canon RF 50mm f1.2L USM - 0960  32000000
8                NEW - MADA_1432 Hand Strap Carabiner    100000
17    Nikon D3400 Kit 18-55mm - GOOD CONDITION |0892|   4850000
7        Secondhand - Nikon AFS 55-200mm VR II - 4014   1950000
9   Secondhand -Canon EF 70-200mm f2.8L IS II USM ...  19900000
14  Sony A6000 Black Kit 16-50mm 3.5-5.6 OSS - MIN...   6650000
18        Sony A7 / Alpha7 BO - MINT CONDITION |2377|   9600000
16          [SECONDHAND] Canon EOS 70D WiFi - BO 3187   6500000

8. kemudian setelah membuat list (dataset) dan create db , tabel dan insert.
9. selanjutnya menampilkan hasil dari insert dataset ke tabel "kamera", source code untuk menampilkan ada dibawah :

In [16]:
import sqlite3
conn = sqlite3.connect('gudangkamera.db')
c = conn.cursor()

c.execute('SELECT * FROM kamera')

meida = c.fetchall()

for i in meida:
    print (i)

('LENSA CANON 17-40MM F/4 L KODE UV', 6000000)
('LENSA SIGMA 50-100MM F1.8 (3836)', 11850000)
('LENSA CANON 70-200MM F/4 L USM KODE UT', 6000000)
('FUJIFILM X-M1 (9066)   LENSA 16-50MM', 4000000)
('LENSA FUJIFILM XF 35MM F/2 WR (7439)', 4500000)
('CANON 50D (6478)   LENSA 18-55MM SC 18XXX', 4800000)
('LIKE-NEW - Canon RF 50mm f1.2L USM - 0960', 32000000)
('Secondhand - Nikon AFS 55-200mm VR II - 4014', 1950000)
('NEW - MADA_1432 Hand Strap Carabiner', 100000)
('Secondhand -Canon EF 70-200mm f2.8L IS II USM - 4870 ', 19900000)
('FUJIFILM X-T20 SILVER (1358)', 9250000)
('FUJIFILM X-T20 (2082)', 9250000)
('Canon 5D Mark III / 5D III BO SC 9rb- Mint Condition |5370|', 22850000)
('Fujifilm X-A3 / Xa3 KIT 16-50MM - MINT CONDITION |3719|', 6300000)
('Sony A6000 Black Kit 16-50mm 3.5-5.6 OSS - MINT CONDITION |', 6650000)
('Canon Eos 70D BO - MINT CONDITION | 2672|', 7700000)
('[SECONDHAND] Canon EOS 70D WiFi - BO 3187', 6500000)
('Nikon D3400 Kit 18-55mm - GOOD CONDITION |0892|', 4850000)
('Sony A7 / Alpha7 BO - MINT CONDITION |2377|', 9600000)
('Canon 60D BO - MINT CONDITION |6887 |', 6300000)